global.factos = [
    "Eres la razón por la que hay instrucciones en los envases de champú.",
    "Si fueras un libro, serías ese que nadie quiere leer.",
    "Tu vida es como un programa de TV que nadie ve.",
    "Eres como un error tipográfico: solo estás ahí para arruinar todo.",
    "Si fueras un producto, serías el que está en oferta porque nadie lo compra.",
    "Eres un recordatorio de lo que no se debe hacer en la vida.",
    "Tu existencia es tan relevante como un archivo en la papelera.",
    "Si fueras un plato, serías uno que nadie quiere probar.",
    "Eres la razón por la que los hombres le temen al compromiso.",
    "Tu personalidad es como un antivirus: nadie quiere instalarla.",
    "Eres la prueba de que la selección natural puede fallar.",
    "Si fueras un color, serías gris: aburrido y sin vida.",
    "Tu vida es como una mala película: nadie quiere ver el final.",
    "Eres como un mal chiste: siempre incomodando a los demás.",
    "Si fueras un animal, serías la mascota que nadie quiere adoptar.",
    "Tu sentido del humor es como un Wi-Fi malo: sin conexión.",
    "Eres como una planta marchita: solo ocupando espacio.",
    "Si fueras un virus informático, serías uno que causa más problemas que soluciones.",
    "Tu imagen es la razón por la que se cubren los espejos.",
    "Eres el ejemplo perfecto de cómo no vivir la vida.",
    "Si fueras un día de la semana, serías lunes: todos te odian.",
    "Eres la razón por la que la gente no cree en el amor verdadero.",
    "Tu vida es un meme, pero nadie se ríe.",
    "Si fueras una app, serías una que nadie quiere descargar.",
    "Eres como una sombra: siempre estás ahí, pero no eres bienvenido.",
    "Tu cerebro es como un disco duro lleno: no puede almacenar más.",
    "Eres como un tren descarrilado: solo causando caos.",
    "Si fueras el clima, serías una tormenta: oscura y destructiva.",
    "Eres como un mensaje en cadena: nadie te quiere, pero todos te reciben.",
    "Tu vida es como un rompecabezas con piezas que nunca encajan.",
    "Si fueras una película, serías una secuela que nadie pidió."
];